export const bibleTitles = {
  titles: [
    { short: 'Быт', full: 'Бытие' },
    { short: 'Исх', full: 'Исход' },
    { short: 'Лев', full: 'Левит' },
    { short: 'Чис', full: 'Числа' },
    { short: 'Втор', full: 'Второзаконие' },
    { short: 'Нав', full: 'Иисус Навин' },
    { short: 'Суд', full: 'Судьи' },
    { short: 'Руф', full: 'Руфь' },
    { short: '1Цар', full: '1-я Царств', min: '1Царств' },
    { short: '2Цар', full: '2-я Царств', min: '2Царств' },
    { short: '3Цар', full: '3-я Царств', min: '3Царств' },
    { short: '4Цар', full: '4-я Царств', min: '4Царств' },
    { short: '1Пар', full: '1-я Паралипоменон', min: '1Паралипоменон' },
    { short: '2Пар', full: '2-я Паралипоменон', min: '2Паралипоменон' },
    { short: 'Ездр', full: 'Ездра' },
    { short: 'Неем', full: 'Неемия' },
    { short: 'Есф', full: 'Есфирь' },
    { short: 'Иов', full: 'Иов' },
    { short: 'Пс', full: 'Псалтирь' },
    { short: 'Прит', full: 'Притчи' },
    { short: 'Еккл', full: 'Екклесиаст' },
    { short: 'Песн', full: 'Песня песней' },
    { short: 'Ис', full: 'Исаия' },
    { short: 'Иер', full: 'Иеремия' },
    { short: 'Плач', full: 'Плач Иеремии' },
    { short: 'Иез', full: 'Иезекииль' },
    { short: 'Дан', full: 'Даниил' },
    { short: 'Ос', full: 'Осия' },
    { short: 'Иоил', full: 'Иоиль' },
    { short: 'Ам', full: 'Амос' },
    { short: 'Авд', full: 'Авдий' },
    { short: 'Ион', full: 'Иона' },
    { short: 'Мих', full: 'Михей' },
    { short: 'Наум', full: 'Наум' },
    { short: 'Авв', full: 'Аввакум' },
    { short: 'Соф', full: 'Софония' },
    { short: 'Агг', full: 'Аггей' },
    { short: 'Зах', full: 'Захария' },
    { short: 'Мал', full: 'Малахия' },
    { short: 'Мат', full: 'От Матфея' },
    { short: 'Мар', full: 'От Марка' },
    { short: 'Лук', full: 'От Луки' },
    { short: 'Ин', full: 'От Иоанна' },
    { short: 'Деян', full: 'Деяния' },
    { short: 'Иак', full: 'Иакова' },
    { short: '1Пет', full: '1-е Петра', min: '1Петра' },
    { short: '2Пет', full: '2-е Петра', min: '2Петра' },
    { short: '1Ин', full: '1-е Иоанна', min: '1Иоанна' },
    { short: '2Ин', full: '2-е Иоанна', min: '2Иоанна' },
    { short: '3Ин', full: '3-е Иоанна', min: '3Иоанна' },
    { short: 'Иуд', full: 'Иуды' },
    { short: 'Рим', full: 'К Римлянам' },
    { short: '1Кор', full: '1-е Коринфянам', min: '1Коринфянам' },
    { short: '2Кор', full: '2-е Коринфянам', min: '2Коринфянам' },
    { short: 'Гал', full: 'К Галатам' },
    { short: 'Еф', full: 'К Ефесянам' },
    { short: 'Флп', full: 'К Филиппийцам' },
    { short: 'Кол', full: 'К Колоссянам' },
    { short: '1Фес', full: '1-е Фессалоникийцам', min: '1Фессалоникийцам' },
    { short: '2Фес', full: '2-е Фессалоникийцам', min: '2Фессалоникийцам' },
    { short: '1Тим', full: '1-е Тимофею', min: '1Тимофею' },
    { short: '2Тим', full: '2-е Тимофею', min: '2Тимофею' },
    { short: 'Тит', full: 'К Титу' },
    { short: 'Флм', full: 'К Филимону' },
    { short: 'Евр', full: 'К Евреям' },
    { short: 'Откр', full: 'Откровение' },
  ],
};

export const checkEachBibleTitles = (
  book: (typeof bibleTitles)['titles'][number],
  checker: (title: string) => boolean,
) => {
  return checker(book.short) || checker(book.full) || checker(book.min ?? '');
};

export const bibleLowerBooks = bibleTitles.titles.map(book => {
  return {
    full: book.full.toLowerCase(),
    short: book.short.toLowerCase(),
    min: book.min?.toLowerCase(),
  };
});
