import { CmComBlockKindKey, IExportableKindProp } from './BlockKind.model';

export const comBlockKindsConfig: IExportableKindProp[] = [
  {
    key: CmComBlockKindKey.Enter,
    title: ['Вступление', 'Вступ'],
    tags: ['вступление', 'вступ', 'интро', 'intro'],
    forChordedBlock: 1,
  },
  {
    key: CmComBlockKindKey.OneWithShift,
    title: ['Куплет', 'Куплет'],
    group: 1,
    isBlockForTextableOnly: true,
  },
  {
    key: CmComBlockKindKey.One,
    title: ['Куплет', 'Куплет'],
    tags: ['куплет', 'купліт', 'куплєт'],
    group: 1,
    isBlockForTextableOnly: true,
  },
  {
    key: CmComBlockKindKey.PTwo,
    title: ['Предприпев', 'Передприспів'],
    tags: [
      'пред припев',
      'предприпев',
      'предприпів',
      'пред припів',
      'передприпів',
      'перед припів',
      'передприспів',
      'перед приспів',
    ],
    isBlockForTextableOnly: true,
  },
  {
    key: CmComBlockKindKey.Two,
    title: ['Припев', 'Приспів'],
    tags: ['припев', 'приспів', 'припів'],
    group: 2,
    isBlockForTextableOnly: true,
  },
  {
    key: CmComBlockKindKey.Bridge,
    title: ['Мост', 'Мост'],
    tags: ['мост', 'бридж', 'брідж', 'міст', 'bridge'],
    group: 3,
    isBlockForTextableOnly: true,
  },
  {
    key: CmComBlockKindKey.Play,
    title: ['Проигрыш', 'Програш'],
    tags: ['проигрыш', 'програш'],
    forChordedBlock: 2,
    isBlockForChordedOnly: true,
  },
  {
    key: CmComBlockKindKey.Modulation,
    title: ['Модуляция', 'Модуляція'],
    tags: ['модуляция', 'модуляція'],
    isModulation: true,
  },
  {
    key: CmComBlockKindKey.Final,
    title: ['Финал', 'Фінал'],
    tags: ['финал', 'фінал', 'фiнал', 'конец', 'концовка', 'кінець', 'final'],
  },
  {
    key: CmComBlockKindKey.Thirdo,
    title: ['Запев', 'Заспів'],
    tags: ['запев', 'заспів', 'запів'],
    group: 4,
    isBlockForTextableOnly: true,
  },
  {
    key: CmComBlockKindKey.Insert,
    title: ['Вставка', 'Вставка'],
    tags: ['вставка'],
  },
  {
    key: CmComBlockKindKey.Plus,
    title: [':ПРОДОЛЖЕНИЕ:', ':ПРОДОВЖЕННЯ:'],
    alt: '+',
    isInherit: true,
    isHeaderNoneForce: true,
    isBlockForTextableOnly: true,
  },
  {
    key: CmComBlockKindKey.PlusPlus,
    title: [':ПРОДОЛЖЕНИЕ С ОТСТУПОМ:', ':ПРОДОВЖЕННЯ З ВІДСТУПОМ:'],
    alt: '++',
    isInherit: true,
    isBlockForTextableOnly: true,
  },
  {
    key: CmComBlockKindKey.Shift,
    title: [':ПРОДОЛЖЕНИЕ СО СМЕЩЕНИЕМ:', ':ПРОДОВЖЕННЯ З ЗМІЩЕННЯМ:'],
    alt: '+>',
    isInherit: true,
    isBlockForTextableOnly: true,
  },
  {
    key: CmComBlockKindKey.PlusPlusShift,
    title: [':ПРОДОЛЖЕНИЕ СО СМЕЩЕНИЕМ И ОТСТУПОМ:', ':ПРОДОВЖЕННЯ З ЗМІЩЕННЯМ ТА ВІДСТУПОМ:'],
    alt: '++>',
    isInherit: true,
    isBlockForTextableOnly: true,
  },
];
