/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './front/routes/__root'
import { Route as TunerRouteImport } from './front/routes/tuner/route'
import { Route as CmRouteImport } from './front/routes/cm/route'
import { Route as BibleRouteImport } from './front/routes/bible/route'
import { Route as IndexImport } from './front/routes/index'
import { Route as TunerIndexImport } from './front/routes/tuner/index'
import { Route as CmIndexImport } from './front/routes/cm/index'
import { Route as BibleIndexImport } from './front/routes/bible/index'
import { Route as TunerIImport } from './front/routes/tuner/i'
import { Route as BibleTranImport } from './front/routes/bible/tran'
import { Route as BibleSearchImport } from './front/routes/bible/search'
import { Route as BibleIImport } from './front/routes/bible/i'
import { Route as otherAppNameRouteImport } from './front/routes/!other.$appName/route'
import { Route as CmPlayerIndexImport } from './front/routes/cm/player/index'
import { Route as CmLiIndexImport } from './front/routes/cm/li/index'
import { Route as CmIIndexImport } from './front/routes/cm/i/index'
import { Route as otherAppNameIndexImport } from './front/routes/!other.$appName/index'
import { Route as CmLiSelImport } from './front/routes/cm/li/sel'
import { Route as CmLiFavImport } from './front/routes/cm/li/fav'
import { Route as CmLiEventsImport } from './front/routes/cm/li/events'
import { Route as otherAppNameSettingsIndexImport } from './front/routes/!other.$appName/settings/index'
import { Route as otherAppNameSchsIndexImport } from './front/routes/!other.$appName/schs/index'
import { Route as otherAppNameAuthIndexImport } from './front/routes/!other.$appName/auth/index'
import { Route as otherAppNameActionsIndexImport } from './front/routes/!other.$appName/actions/index'
import { Route as CmLiCatCatwImport } from './front/routes/cm/li/cat.$catw'
import { Route as otherAppNameSettingsRightsImport } from './front/routes/!other.$appName/settings/rights'
import { Route as otherAppNameSettingsConsoleImport } from './front/routes/!other.$appName/settings/console'
import { Route as StoragesIRackwSumIndexImport } from './front/routes/storages/i/$rackw/sum/index'
import { Route as otherAppNameSettingsNounpronsIndexImport } from './front/routes/!other.$appName/settings/noun_prons/index'
import { Route as otherAppNameActionsFilesIndexImport } from './front/routes/!other.$appName/actions/files/index'
import { Route as otherAppNameActionsDownIndexImport } from './front/routes/!other.$appName/actions/down/index'

// Create Virtual Routes

const StoragesRouteLazyImport = createFileRoute('/storages')()
const QRouteLazyImport = createFileRoute('/q')()
const GamerRouteLazyImport = createFileRoute('/gamer')()
const ScheduleDayIndexLazyImport = createFileRoute('/schedule-day/')()
const PresentationIndexLazyImport = createFileRoute('/presentation/')()
const GamerIndexLazyImport = createFileRoute('/gamer/')()
const QILazyImport = createFileRoute('/q/i')()
const CmEditRouteLazyImport = createFileRoute('/cm/edit')()
const StoragesIIndexLazyImport = createFileRoute('/storages/i/')()
const ScheduleDaySchwIndexLazyImport = createFileRoute('/schedule-day/$schw/')()
const QRIndexLazyImport = createFileRoute('/q/r/')()
const QAIndexLazyImport = createFileRoute('/q/a/')()
const GamerIIndexLazyImport = createFileRoute('/gamer/i/')()
const CmEditIndexLazyImport = createFileRoute('/cm/edit/')()
const QRBlankLazyImport = createFileRoute('/q/r/$blank')()
const QABlankLazyImport = createFileRoute('/q/a/$blank')()
const CmEditMp3RulesLazyImport = createFileRoute('/cm/edit/mp3Rules')()
const CmEditEventsLazyImport = createFileRoute('/cm/edit/events')()
const CmEditEELazyImport = createFileRoute('/cm/edit/e-e')()
const CmEditConstantLazyImport = createFileRoute('/cm/edit/constant')()
const CmEditChordLazyImport = createFileRoute('/cm/edit/chord')()
const StoragesIRackwIndexLazyImport = createFileRoute('/storages/i/$rackw/')()
const GamerIMemoryGiantIndexLazyImport = createFileRoute(
  '/gamer/i/memory-giant/',
)()
const CmEditComsIndexLazyImport = createFileRoute('/cm/edit/coms/')()
const StoragesIRackwEditIndexLazyImport = createFileRoute(
  '/storages/i/$rackw/edit/',
)()
const StoragesIRackwCardiIndexLazyImport = createFileRoute(
  '/storages/i/$rackw/$cardi/',
)()
const CmEditComsComwIndexLazyImport = createFileRoute('/cm/edit/coms/$comw/')()
const CmEditComsComwTabIndexLazyImport = createFileRoute(
  '/cm/edit/coms/$comw/$tab/',
)()

// Create/Update Routes

const StoragesRouteLazyRoute = StoragesRouteLazyImport.update({
  id: '/storages',
  path: '/storages',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./front/routes/storages/route.lazy').then((d) => d.Route),
)

const QRouteLazyRoute = QRouteLazyImport.update({
  id: '/q',
  path: '/q',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./front/routes/q/route.lazy').then((d) => d.Route))

const GamerRouteLazyRoute = GamerRouteLazyImport.update({
  id: '/gamer',
  path: '/gamer',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./front/routes/gamer/route.lazy').then((d) => d.Route),
)

const TunerRouteRoute = TunerRouteImport.update({
  id: '/tuner',
  path: '/tuner',
  getParentRoute: () => rootRoute,
} as any)

const CmRouteRoute = CmRouteImport.update({
  id: '/cm',
  path: '/cm',
  getParentRoute: () => rootRoute,
} as any)

const BibleRouteRoute = BibleRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ScheduleDayIndexLazyRoute = ScheduleDayIndexLazyImport.update({
  id: '/schedule-day/',
  path: '/schedule-day/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./front/routes/schedule-day/index.lazy').then((d) => d.Route),
)

const PresentationIndexLazyRoute = PresentationIndexLazyImport.update({
  id: '/presentation/',
  path: '/presentation/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./front/routes/presentation/index.lazy').then((d) => d.Route),
)

const GamerIndexLazyRoute = GamerIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamerRouteLazyRoute,
} as any).lazy(() =>
  import('./front/routes/gamer/index.lazy').then((d) => d.Route),
)

const TunerIndexRoute = TunerIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TunerRouteRoute,
} as any)

const CmIndexRoute = CmIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CmRouteRoute,
} as any)

const BibleIndexRoute = BibleIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibleRouteRoute,
} as any)

const QILazyRoute = QILazyImport.update({
  id: '/i',
  path: '/i',
  getParentRoute: () => QRouteLazyRoute,
} as any).lazy(() => import('./front/routes/q/i.lazy').then((d) => d.Route))

const CmEditRouteLazyRoute = CmEditRouteLazyImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CmRouteRoute,
} as any).lazy(() =>
  import('./front/routes/cm/edit/route.lazy').then((d) => d.Route),
)

const TunerIRoute = TunerIImport.update({
  id: '/i',
  path: '/i',
  getParentRoute: () => TunerRouteRoute,
} as any)

const BibleTranRoute = BibleTranImport.update({
  id: '/tran',
  path: '/tran',
  getParentRoute: () => BibleRouteRoute,
} as any)

const BibleSearchRoute = BibleSearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => BibleRouteRoute,
} as any)

const BibleIRoute = BibleIImport.update({
  id: '/i',
  path: '/i',
  getParentRoute: () => BibleRouteRoute,
} as any)

const otherAppNameRouteRoute = otherAppNameRouteImport.update({
  id: '/!other/$appName',
  path: '/!other/$appName',
  getParentRoute: () => rootRoute,
} as any)

const StoragesIIndexLazyRoute = StoragesIIndexLazyImport.update({
  id: '/i/',
  path: '/i/',
  getParentRoute: () => StoragesRouteLazyRoute,
} as any).lazy(() =>
  import('./front/routes/storages/i/index.lazy').then((d) => d.Route),
)

const ScheduleDaySchwIndexLazyRoute = ScheduleDaySchwIndexLazyImport.update({
  id: '/schedule-day/$schw/',
  path: '/schedule-day/$schw/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./front/routes/schedule-day/$schw/index.lazy').then((d) => d.Route),
)

const QRIndexLazyRoute = QRIndexLazyImport.update({
  id: '/r/',
  path: '/r/',
  getParentRoute: () => QRouteLazyRoute,
} as any).lazy(() =>
  import('./front/routes/q/r/index.lazy').then((d) => d.Route),
)

const QAIndexLazyRoute = QAIndexLazyImport.update({
  id: '/a/',
  path: '/a/',
  getParentRoute: () => QRouteLazyRoute,
} as any).lazy(() =>
  import('./front/routes/q/a/index.lazy').then((d) => d.Route),
)

const GamerIIndexLazyRoute = GamerIIndexLazyImport.update({
  id: '/i/',
  path: '/i/',
  getParentRoute: () => GamerRouteLazyRoute,
} as any).lazy(() =>
  import('./front/routes/gamer/i/index.lazy').then((d) => d.Route),
)

const CmEditIndexLazyRoute = CmEditIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CmEditRouteLazyRoute,
} as any).lazy(() =>
  import('./front/routes/cm/edit/index.lazy').then((d) => d.Route),
)

const CmPlayerIndexRoute = CmPlayerIndexImport.update({
  id: '/player/',
  path: '/player/',
  getParentRoute: () => CmRouteRoute,
} as any)

const CmLiIndexRoute = CmLiIndexImport.update({
  id: '/li/',
  path: '/li/',
  getParentRoute: () => CmRouteRoute,
} as any)

const CmIIndexRoute = CmIIndexImport.update({
  id: '/i/',
  path: '/i/',
  getParentRoute: () => CmRouteRoute,
} as any)

const otherAppNameIndexRoute = otherAppNameIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => otherAppNameRouteRoute,
} as any)

const QRBlankLazyRoute = QRBlankLazyImport.update({
  id: '/r/$blank',
  path: '/r/$blank',
  getParentRoute: () => QRouteLazyRoute,
} as any).lazy(() =>
  import('./front/routes/q/r/$blank.lazy').then((d) => d.Route),
)

const QABlankLazyRoute = QABlankLazyImport.update({
  id: '/a/$blank',
  path: '/a/$blank',
  getParentRoute: () => QRouteLazyRoute,
} as any).lazy(() =>
  import('./front/routes/q/a/$blank.lazy').then((d) => d.Route),
)

const CmEditMp3RulesLazyRoute = CmEditMp3RulesLazyImport.update({
  id: '/mp3Rules',
  path: '/mp3Rules',
  getParentRoute: () => CmEditRouteLazyRoute,
} as any).lazy(() =>
  import('./front/routes/cm/edit/mp3Rules.lazy').then((d) => d.Route),
)

const CmEditEventsLazyRoute = CmEditEventsLazyImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => CmEditRouteLazyRoute,
} as any).lazy(() =>
  import('./front/routes/cm/edit/events.lazy').then((d) => d.Route),
)

const CmEditEELazyRoute = CmEditEELazyImport.update({
  id: '/e-e',
  path: '/e-e',
  getParentRoute: () => CmEditRouteLazyRoute,
} as any).lazy(() =>
  import('./front/routes/cm/edit/e-e.lazy').then((d) => d.Route),
)

const CmEditConstantLazyRoute = CmEditConstantLazyImport.update({
  id: '/constant',
  path: '/constant',
  getParentRoute: () => CmEditRouteLazyRoute,
} as any).lazy(() =>
  import('./front/routes/cm/edit/constant.lazy').then((d) => d.Route),
)

const CmEditChordLazyRoute = CmEditChordLazyImport.update({
  id: '/chord',
  path: '/chord',
  getParentRoute: () => CmEditRouteLazyRoute,
} as any).lazy(() =>
  import('./front/routes/cm/edit/chord.lazy').then((d) => d.Route),
)

const CmLiSelRoute = CmLiSelImport.update({
  id: '/li/sel',
  path: '/li/sel',
  getParentRoute: () => CmRouteRoute,
} as any)

const CmLiFavRoute = CmLiFavImport.update({
  id: '/li/fav',
  path: '/li/fav',
  getParentRoute: () => CmRouteRoute,
} as any)

const CmLiEventsRoute = CmLiEventsImport.update({
  id: '/li/events',
  path: '/li/events',
  getParentRoute: () => CmRouteRoute,
} as any)

const StoragesIRackwIndexLazyRoute = StoragesIRackwIndexLazyImport.update({
  id: '/i/$rackw/',
  path: '/i/$rackw/',
  getParentRoute: () => StoragesRouteLazyRoute,
} as any).lazy(() =>
  import('./front/routes/storages/i/$rackw/index.lazy').then((d) => d.Route),
)

const GamerIMemoryGiantIndexLazyRoute = GamerIMemoryGiantIndexLazyImport.update(
  {
    id: '/i/memory-giant/',
    path: '/i/memory-giant/',
    getParentRoute: () => GamerRouteLazyRoute,
  } as any,
).lazy(() =>
  import('./front/routes/gamer/i/memory-giant/index.lazy').then((d) => d.Route),
)

const CmEditComsIndexLazyRoute = CmEditComsIndexLazyImport.update({
  id: '/coms/',
  path: '/coms/',
  getParentRoute: () => CmEditRouteLazyRoute,
} as any).lazy(() =>
  import('./front/routes/cm/edit/coms/index.lazy').then((d) => d.Route),
)

const otherAppNameSettingsIndexRoute = otherAppNameSettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => otherAppNameRouteRoute,
} as any)

const otherAppNameSchsIndexRoute = otherAppNameSchsIndexImport.update({
  id: '/schs/',
  path: '/schs/',
  getParentRoute: () => otherAppNameRouteRoute,
} as any)

const otherAppNameAuthIndexRoute = otherAppNameAuthIndexImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => otherAppNameRouteRoute,
} as any)

const otherAppNameActionsIndexRoute = otherAppNameActionsIndexImport.update({
  id: '/actions/',
  path: '/actions/',
  getParentRoute: () => otherAppNameRouteRoute,
} as any)

const CmLiCatCatwRoute = CmLiCatCatwImport.update({
  id: '/li/cat/$catw',
  path: '/li/cat/$catw',
  getParentRoute: () => CmRouteRoute,
} as any)

const otherAppNameSettingsRightsRoute = otherAppNameSettingsRightsImport.update(
  {
    id: '/settings/rights',
    path: '/settings/rights',
    getParentRoute: () => otherAppNameRouteRoute,
  } as any,
)

const otherAppNameSettingsConsoleRoute =
  otherAppNameSettingsConsoleImport.update({
    id: '/settings/console',
    path: '/settings/console',
    getParentRoute: () => otherAppNameRouteRoute,
  } as any)

const StoragesIRackwEditIndexLazyRoute =
  StoragesIRackwEditIndexLazyImport.update({
    id: '/i/$rackw/edit/',
    path: '/i/$rackw/edit/',
    getParentRoute: () => StoragesRouteLazyRoute,
  } as any).lazy(() =>
    import('./front/routes/storages/i/$rackw/edit/index.lazy').then(
      (d) => d.Route,
    ),
  )

const StoragesIRackwCardiIndexLazyRoute =
  StoragesIRackwCardiIndexLazyImport.update({
    id: '/i/$rackw/$cardi/',
    path: '/i/$rackw/$cardi/',
    getParentRoute: () => StoragesRouteLazyRoute,
  } as any).lazy(() =>
    import('./front/routes/storages/i/$rackw/$cardi/index.lazy').then(
      (d) => d.Route,
    ),
  )

const CmEditComsComwIndexLazyRoute = CmEditComsComwIndexLazyImport.update({
  id: '/coms/$comw/',
  path: '/coms/$comw/',
  getParentRoute: () => CmEditRouteLazyRoute,
} as any).lazy(() =>
  import('./front/routes/cm/edit/coms/$comw/index.lazy').then((d) => d.Route),
)

const StoragesIRackwSumIndexRoute = StoragesIRackwSumIndexImport.update({
  id: '/i/$rackw/sum/',
  path: '/i/$rackw/sum/',
  getParentRoute: () => StoragesRouteLazyRoute,
} as any)

const otherAppNameSettingsNounpronsIndexRoute =
  otherAppNameSettingsNounpronsIndexImport.update({
    id: '/settings/noun_prons/',
    path: '/settings/noun_prons/',
    getParentRoute: () => otherAppNameRouteRoute,
  } as any)

const otherAppNameActionsFilesIndexRoute =
  otherAppNameActionsFilesIndexImport.update({
    id: '/actions/files/',
    path: '/actions/files/',
    getParentRoute: () => otherAppNameRouteRoute,
  } as any)

const otherAppNameActionsDownIndexRoute =
  otherAppNameActionsDownIndexImport.update({
    id: '/actions/down/',
    path: '/actions/down/',
    getParentRoute: () => otherAppNameRouteRoute,
  } as any)

const CmEditComsComwTabIndexLazyRoute = CmEditComsComwTabIndexLazyImport.update(
  {
    id: '/coms/$comw/$tab/',
    path: '/coms/$comw/$tab/',
    getParentRoute: () => CmEditRouteLazyRoute,
  } as any,
).lazy(() =>
  import('./front/routes/cm/edit/coms/$comw/$tab/index.lazy').then(
    (d) => d.Route,
  ),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bible': {
      id: '/bible'
      path: '/bible'
      fullPath: '/bible'
      preLoaderRoute: typeof BibleRouteImport
      parentRoute: typeof rootRoute
    }
    '/cm': {
      id: '/cm'
      path: '/cm'
      fullPath: '/cm'
      preLoaderRoute: typeof CmRouteImport
      parentRoute: typeof rootRoute
    }
    '/tuner': {
      id: '/tuner'
      path: '/tuner'
      fullPath: '/tuner'
      preLoaderRoute: typeof TunerRouteImport
      parentRoute: typeof rootRoute
    }
    '/gamer': {
      id: '/gamer'
      path: '/gamer'
      fullPath: '/gamer'
      preLoaderRoute: typeof GamerRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/q': {
      id: '/q'
      path: '/q'
      fullPath: '/q'
      preLoaderRoute: typeof QRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/storages': {
      id: '/storages'
      path: '/storages'
      fullPath: '/storages'
      preLoaderRoute: typeof StoragesRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/!other/$appName': {
      id: '/!other/$appName'
      path: '/!other/$appName'
      fullPath: '/!other/$appName'
      preLoaderRoute: typeof otherAppNameRouteImport
      parentRoute: typeof rootRoute
    }
    '/bible/i': {
      id: '/bible/i'
      path: '/i'
      fullPath: '/bible/i'
      preLoaderRoute: typeof BibleIImport
      parentRoute: typeof BibleRouteImport
    }
    '/bible/search': {
      id: '/bible/search'
      path: '/search'
      fullPath: '/bible/search'
      preLoaderRoute: typeof BibleSearchImport
      parentRoute: typeof BibleRouteImport
    }
    '/bible/tran': {
      id: '/bible/tran'
      path: '/tran'
      fullPath: '/bible/tran'
      preLoaderRoute: typeof BibleTranImport
      parentRoute: typeof BibleRouteImport
    }
    '/tuner/i': {
      id: '/tuner/i'
      path: '/i'
      fullPath: '/tuner/i'
      preLoaderRoute: typeof TunerIImport
      parentRoute: typeof TunerRouteImport
    }
    '/cm/edit': {
      id: '/cm/edit'
      path: '/edit'
      fullPath: '/cm/edit'
      preLoaderRoute: typeof CmEditRouteLazyImport
      parentRoute: typeof CmRouteImport
    }
    '/q/i': {
      id: '/q/i'
      path: '/i'
      fullPath: '/q/i'
      preLoaderRoute: typeof QILazyImport
      parentRoute: typeof QRouteLazyImport
    }
    '/bible/': {
      id: '/bible/'
      path: '/'
      fullPath: '/bible/'
      preLoaderRoute: typeof BibleIndexImport
      parentRoute: typeof BibleRouteImport
    }
    '/cm/': {
      id: '/cm/'
      path: '/'
      fullPath: '/cm/'
      preLoaderRoute: typeof CmIndexImport
      parentRoute: typeof CmRouteImport
    }
    '/tuner/': {
      id: '/tuner/'
      path: '/'
      fullPath: '/tuner/'
      preLoaderRoute: typeof TunerIndexImport
      parentRoute: typeof TunerRouteImport
    }
    '/gamer/': {
      id: '/gamer/'
      path: '/'
      fullPath: '/gamer/'
      preLoaderRoute: typeof GamerIndexLazyImport
      parentRoute: typeof GamerRouteLazyImport
    }
    '/presentation/': {
      id: '/presentation/'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/schedule-day/': {
      id: '/schedule-day/'
      path: '/schedule-day'
      fullPath: '/schedule-day'
      preLoaderRoute: typeof ScheduleDayIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cm/li/events': {
      id: '/cm/li/events'
      path: '/li/events'
      fullPath: '/cm/li/events'
      preLoaderRoute: typeof CmLiEventsImport
      parentRoute: typeof CmRouteImport
    }
    '/cm/li/fav': {
      id: '/cm/li/fav'
      path: '/li/fav'
      fullPath: '/cm/li/fav'
      preLoaderRoute: typeof CmLiFavImport
      parentRoute: typeof CmRouteImport
    }
    '/cm/li/sel': {
      id: '/cm/li/sel'
      path: '/li/sel'
      fullPath: '/cm/li/sel'
      preLoaderRoute: typeof CmLiSelImport
      parentRoute: typeof CmRouteImport
    }
    '/cm/edit/chord': {
      id: '/cm/edit/chord'
      path: '/chord'
      fullPath: '/cm/edit/chord'
      preLoaderRoute: typeof CmEditChordLazyImport
      parentRoute: typeof CmEditRouteLazyImport
    }
    '/cm/edit/constant': {
      id: '/cm/edit/constant'
      path: '/constant'
      fullPath: '/cm/edit/constant'
      preLoaderRoute: typeof CmEditConstantLazyImport
      parentRoute: typeof CmEditRouteLazyImport
    }
    '/cm/edit/e-e': {
      id: '/cm/edit/e-e'
      path: '/e-e'
      fullPath: '/cm/edit/e-e'
      preLoaderRoute: typeof CmEditEELazyImport
      parentRoute: typeof CmEditRouteLazyImport
    }
    '/cm/edit/events': {
      id: '/cm/edit/events'
      path: '/events'
      fullPath: '/cm/edit/events'
      preLoaderRoute: typeof CmEditEventsLazyImport
      parentRoute: typeof CmEditRouteLazyImport
    }
    '/cm/edit/mp3Rules': {
      id: '/cm/edit/mp3Rules'
      path: '/mp3Rules'
      fullPath: '/cm/edit/mp3Rules'
      preLoaderRoute: typeof CmEditMp3RulesLazyImport
      parentRoute: typeof CmEditRouteLazyImport
    }
    '/q/a/$blank': {
      id: '/q/a/$blank'
      path: '/a/$blank'
      fullPath: '/q/a/$blank'
      preLoaderRoute: typeof QABlankLazyImport
      parentRoute: typeof QRouteLazyImport
    }
    '/q/r/$blank': {
      id: '/q/r/$blank'
      path: '/r/$blank'
      fullPath: '/q/r/$blank'
      preLoaderRoute: typeof QRBlankLazyImport
      parentRoute: typeof QRouteLazyImport
    }
    '/!other/$appName/': {
      id: '/!other/$appName/'
      path: '/'
      fullPath: '/!other/$appName/'
      preLoaderRoute: typeof otherAppNameIndexImport
      parentRoute: typeof otherAppNameRouteImport
    }
    '/cm/i/': {
      id: '/cm/i/'
      path: '/i'
      fullPath: '/cm/i'
      preLoaderRoute: typeof CmIIndexImport
      parentRoute: typeof CmRouteImport
    }
    '/cm/li/': {
      id: '/cm/li/'
      path: '/li'
      fullPath: '/cm/li'
      preLoaderRoute: typeof CmLiIndexImport
      parentRoute: typeof CmRouteImport
    }
    '/cm/player/': {
      id: '/cm/player/'
      path: '/player'
      fullPath: '/cm/player'
      preLoaderRoute: typeof CmPlayerIndexImport
      parentRoute: typeof CmRouteImport
    }
    '/cm/edit/': {
      id: '/cm/edit/'
      path: '/'
      fullPath: '/cm/edit/'
      preLoaderRoute: typeof CmEditIndexLazyImport
      parentRoute: typeof CmEditRouteLazyImport
    }
    '/gamer/i/': {
      id: '/gamer/i/'
      path: '/i'
      fullPath: '/gamer/i'
      preLoaderRoute: typeof GamerIIndexLazyImport
      parentRoute: typeof GamerRouteLazyImport
    }
    '/q/a/': {
      id: '/q/a/'
      path: '/a'
      fullPath: '/q/a'
      preLoaderRoute: typeof QAIndexLazyImport
      parentRoute: typeof QRouteLazyImport
    }
    '/q/r/': {
      id: '/q/r/'
      path: '/r'
      fullPath: '/q/r'
      preLoaderRoute: typeof QRIndexLazyImport
      parentRoute: typeof QRouteLazyImport
    }
    '/schedule-day/$schw/': {
      id: '/schedule-day/$schw/'
      path: '/schedule-day/$schw'
      fullPath: '/schedule-day/$schw'
      preLoaderRoute: typeof ScheduleDaySchwIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/storages/i/': {
      id: '/storages/i/'
      path: '/i'
      fullPath: '/storages/i'
      preLoaderRoute: typeof StoragesIIndexLazyImport
      parentRoute: typeof StoragesRouteLazyImport
    }
    '/!other/$appName/settings/console': {
      id: '/!other/$appName/settings/console'
      path: '/settings/console'
      fullPath: '/!other/$appName/settings/console'
      preLoaderRoute: typeof otherAppNameSettingsConsoleImport
      parentRoute: typeof otherAppNameRouteImport
    }
    '/!other/$appName/settings/rights': {
      id: '/!other/$appName/settings/rights'
      path: '/settings/rights'
      fullPath: '/!other/$appName/settings/rights'
      preLoaderRoute: typeof otherAppNameSettingsRightsImport
      parentRoute: typeof otherAppNameRouteImport
    }
    '/cm/li/cat/$catw': {
      id: '/cm/li/cat/$catw'
      path: '/li/cat/$catw'
      fullPath: '/cm/li/cat/$catw'
      preLoaderRoute: typeof CmLiCatCatwImport
      parentRoute: typeof CmRouteImport
    }
    '/!other/$appName/actions/': {
      id: '/!other/$appName/actions/'
      path: '/actions'
      fullPath: '/!other/$appName/actions'
      preLoaderRoute: typeof otherAppNameActionsIndexImport
      parentRoute: typeof otherAppNameRouteImport
    }
    '/!other/$appName/auth/': {
      id: '/!other/$appName/auth/'
      path: '/auth'
      fullPath: '/!other/$appName/auth'
      preLoaderRoute: typeof otherAppNameAuthIndexImport
      parentRoute: typeof otherAppNameRouteImport
    }
    '/!other/$appName/schs/': {
      id: '/!other/$appName/schs/'
      path: '/schs'
      fullPath: '/!other/$appName/schs'
      preLoaderRoute: typeof otherAppNameSchsIndexImport
      parentRoute: typeof otherAppNameRouteImport
    }
    '/!other/$appName/settings/': {
      id: '/!other/$appName/settings/'
      path: '/settings'
      fullPath: '/!other/$appName/settings'
      preLoaderRoute: typeof otherAppNameSettingsIndexImport
      parentRoute: typeof otherAppNameRouteImport
    }
    '/cm/edit/coms/': {
      id: '/cm/edit/coms/'
      path: '/coms'
      fullPath: '/cm/edit/coms'
      preLoaderRoute: typeof CmEditComsIndexLazyImport
      parentRoute: typeof CmEditRouteLazyImport
    }
    '/gamer/i/memory-giant/': {
      id: '/gamer/i/memory-giant/'
      path: '/i/memory-giant'
      fullPath: '/gamer/i/memory-giant'
      preLoaderRoute: typeof GamerIMemoryGiantIndexLazyImport
      parentRoute: typeof GamerRouteLazyImport
    }
    '/storages/i/$rackw/': {
      id: '/storages/i/$rackw/'
      path: '/i/$rackw'
      fullPath: '/storages/i/$rackw'
      preLoaderRoute: typeof StoragesIRackwIndexLazyImport
      parentRoute: typeof StoragesRouteLazyImport
    }
    '/!other/$appName/actions/down/': {
      id: '/!other/$appName/actions/down/'
      path: '/actions/down'
      fullPath: '/!other/$appName/actions/down'
      preLoaderRoute: typeof otherAppNameActionsDownIndexImport
      parentRoute: typeof otherAppNameRouteImport
    }
    '/!other/$appName/actions/files/': {
      id: '/!other/$appName/actions/files/'
      path: '/actions/files'
      fullPath: '/!other/$appName/actions/files'
      preLoaderRoute: typeof otherAppNameActionsFilesIndexImport
      parentRoute: typeof otherAppNameRouteImport
    }
    '/!other/$appName/settings/noun_prons/': {
      id: '/!other/$appName/settings/noun_prons/'
      path: '/settings/noun_prons'
      fullPath: '/!other/$appName/settings/noun_prons'
      preLoaderRoute: typeof otherAppNameSettingsNounpronsIndexImport
      parentRoute: typeof otherAppNameRouteImport
    }
    '/storages/i/$rackw/sum/': {
      id: '/storages/i/$rackw/sum/'
      path: '/i/$rackw/sum'
      fullPath: '/storages/i/$rackw/sum'
      preLoaderRoute: typeof StoragesIRackwSumIndexImport
      parentRoute: typeof StoragesRouteLazyImport
    }
    '/cm/edit/coms/$comw/': {
      id: '/cm/edit/coms/$comw/'
      path: '/coms/$comw'
      fullPath: '/cm/edit/coms/$comw'
      preLoaderRoute: typeof CmEditComsComwIndexLazyImport
      parentRoute: typeof CmEditRouteLazyImport
    }
    '/storages/i/$rackw/$cardi/': {
      id: '/storages/i/$rackw/$cardi/'
      path: '/i/$rackw/$cardi'
      fullPath: '/storages/i/$rackw/$cardi'
      preLoaderRoute: typeof StoragesIRackwCardiIndexLazyImport
      parentRoute: typeof StoragesRouteLazyImport
    }
    '/storages/i/$rackw/edit/': {
      id: '/storages/i/$rackw/edit/'
      path: '/i/$rackw/edit'
      fullPath: '/storages/i/$rackw/edit'
      preLoaderRoute: typeof StoragesIRackwEditIndexLazyImport
      parentRoute: typeof StoragesRouteLazyImport
    }
    '/cm/edit/coms/$comw/$tab/': {
      id: '/cm/edit/coms/$comw/$tab/'
      path: '/coms/$comw/$tab'
      fullPath: '/cm/edit/coms/$comw/$tab'
      preLoaderRoute: typeof CmEditComsComwTabIndexLazyImport
      parentRoute: typeof CmEditRouteLazyImport
    }
  }
}

// Create and export the route tree

interface BibleRouteRouteChildren {
  BibleIRoute: typeof BibleIRoute
  BibleSearchRoute: typeof BibleSearchRoute
  BibleTranRoute: typeof BibleTranRoute
  BibleIndexRoute: typeof BibleIndexRoute
}

const BibleRouteRouteChildren: BibleRouteRouteChildren = {
  BibleIRoute: BibleIRoute,
  BibleSearchRoute: BibleSearchRoute,
  BibleTranRoute: BibleTranRoute,
  BibleIndexRoute: BibleIndexRoute,
}

const BibleRouteRouteWithChildren = BibleRouteRoute._addFileChildren(
  BibleRouteRouteChildren,
)

interface CmEditRouteLazyRouteChildren {
  CmEditChordLazyRoute: typeof CmEditChordLazyRoute
  CmEditConstantLazyRoute: typeof CmEditConstantLazyRoute
  CmEditEELazyRoute: typeof CmEditEELazyRoute
  CmEditEventsLazyRoute: typeof CmEditEventsLazyRoute
  CmEditMp3RulesLazyRoute: typeof CmEditMp3RulesLazyRoute
  CmEditIndexLazyRoute: typeof CmEditIndexLazyRoute
  CmEditComsIndexLazyRoute: typeof CmEditComsIndexLazyRoute
  CmEditComsComwIndexLazyRoute: typeof CmEditComsComwIndexLazyRoute
  CmEditComsComwTabIndexLazyRoute: typeof CmEditComsComwTabIndexLazyRoute
}

const CmEditRouteLazyRouteChildren: CmEditRouteLazyRouteChildren = {
  CmEditChordLazyRoute: CmEditChordLazyRoute,
  CmEditConstantLazyRoute: CmEditConstantLazyRoute,
  CmEditEELazyRoute: CmEditEELazyRoute,
  CmEditEventsLazyRoute: CmEditEventsLazyRoute,
  CmEditMp3RulesLazyRoute: CmEditMp3RulesLazyRoute,
  CmEditIndexLazyRoute: CmEditIndexLazyRoute,
  CmEditComsIndexLazyRoute: CmEditComsIndexLazyRoute,
  CmEditComsComwIndexLazyRoute: CmEditComsComwIndexLazyRoute,
  CmEditComsComwTabIndexLazyRoute: CmEditComsComwTabIndexLazyRoute,
}

const CmEditRouteLazyRouteWithChildren = CmEditRouteLazyRoute._addFileChildren(
  CmEditRouteLazyRouteChildren,
)

interface CmRouteRouteChildren {
  CmEditRouteLazyRoute: typeof CmEditRouteLazyRouteWithChildren
  CmIndexRoute: typeof CmIndexRoute
  CmLiEventsRoute: typeof CmLiEventsRoute
  CmLiFavRoute: typeof CmLiFavRoute
  CmLiSelRoute: typeof CmLiSelRoute
  CmIIndexRoute: typeof CmIIndexRoute
  CmLiIndexRoute: typeof CmLiIndexRoute
  CmPlayerIndexRoute: typeof CmPlayerIndexRoute
  CmLiCatCatwRoute: typeof CmLiCatCatwRoute
}

const CmRouteRouteChildren: CmRouteRouteChildren = {
  CmEditRouteLazyRoute: CmEditRouteLazyRouteWithChildren,
  CmIndexRoute: CmIndexRoute,
  CmLiEventsRoute: CmLiEventsRoute,
  CmLiFavRoute: CmLiFavRoute,
  CmLiSelRoute: CmLiSelRoute,
  CmIIndexRoute: CmIIndexRoute,
  CmLiIndexRoute: CmLiIndexRoute,
  CmPlayerIndexRoute: CmPlayerIndexRoute,
  CmLiCatCatwRoute: CmLiCatCatwRoute,
}

const CmRouteRouteWithChildren =
  CmRouteRoute._addFileChildren(CmRouteRouteChildren)

interface TunerRouteRouteChildren {
  TunerIRoute: typeof TunerIRoute
  TunerIndexRoute: typeof TunerIndexRoute
}

const TunerRouteRouteChildren: TunerRouteRouteChildren = {
  TunerIRoute: TunerIRoute,
  TunerIndexRoute: TunerIndexRoute,
}

const TunerRouteRouteWithChildren = TunerRouteRoute._addFileChildren(
  TunerRouteRouteChildren,
)

interface GamerRouteLazyRouteChildren {
  GamerIndexLazyRoute: typeof GamerIndexLazyRoute
  GamerIIndexLazyRoute: typeof GamerIIndexLazyRoute
  GamerIMemoryGiantIndexLazyRoute: typeof GamerIMemoryGiantIndexLazyRoute
}

const GamerRouteLazyRouteChildren: GamerRouteLazyRouteChildren = {
  GamerIndexLazyRoute: GamerIndexLazyRoute,
  GamerIIndexLazyRoute: GamerIIndexLazyRoute,
  GamerIMemoryGiantIndexLazyRoute: GamerIMemoryGiantIndexLazyRoute,
}

const GamerRouteLazyRouteWithChildren = GamerRouteLazyRoute._addFileChildren(
  GamerRouteLazyRouteChildren,
)

interface QRouteLazyRouteChildren {
  QILazyRoute: typeof QILazyRoute
  QABlankLazyRoute: typeof QABlankLazyRoute
  QRBlankLazyRoute: typeof QRBlankLazyRoute
  QAIndexLazyRoute: typeof QAIndexLazyRoute
  QRIndexLazyRoute: typeof QRIndexLazyRoute
}

const QRouteLazyRouteChildren: QRouteLazyRouteChildren = {
  QILazyRoute: QILazyRoute,
  QABlankLazyRoute: QABlankLazyRoute,
  QRBlankLazyRoute: QRBlankLazyRoute,
  QAIndexLazyRoute: QAIndexLazyRoute,
  QRIndexLazyRoute: QRIndexLazyRoute,
}

const QRouteLazyRouteWithChildren = QRouteLazyRoute._addFileChildren(
  QRouteLazyRouteChildren,
)

interface StoragesRouteLazyRouteChildren {
  StoragesIIndexLazyRoute: typeof StoragesIIndexLazyRoute
  StoragesIRackwIndexLazyRoute: typeof StoragesIRackwIndexLazyRoute
  StoragesIRackwSumIndexRoute: typeof StoragesIRackwSumIndexRoute
  StoragesIRackwCardiIndexLazyRoute: typeof StoragesIRackwCardiIndexLazyRoute
  StoragesIRackwEditIndexLazyRoute: typeof StoragesIRackwEditIndexLazyRoute
}

const StoragesRouteLazyRouteChildren: StoragesRouteLazyRouteChildren = {
  StoragesIIndexLazyRoute: StoragesIIndexLazyRoute,
  StoragesIRackwIndexLazyRoute: StoragesIRackwIndexLazyRoute,
  StoragesIRackwSumIndexRoute: StoragesIRackwSumIndexRoute,
  StoragesIRackwCardiIndexLazyRoute: StoragesIRackwCardiIndexLazyRoute,
  StoragesIRackwEditIndexLazyRoute: StoragesIRackwEditIndexLazyRoute,
}

const StoragesRouteLazyRouteWithChildren =
  StoragesRouteLazyRoute._addFileChildren(StoragesRouteLazyRouteChildren)

interface otherAppNameRouteRouteChildren {
  otherAppNameIndexRoute: typeof otherAppNameIndexRoute
  otherAppNameSettingsConsoleRoute: typeof otherAppNameSettingsConsoleRoute
  otherAppNameSettingsRightsRoute: typeof otherAppNameSettingsRightsRoute
  otherAppNameActionsIndexRoute: typeof otherAppNameActionsIndexRoute
  otherAppNameAuthIndexRoute: typeof otherAppNameAuthIndexRoute
  otherAppNameSchsIndexRoute: typeof otherAppNameSchsIndexRoute
  otherAppNameSettingsIndexRoute: typeof otherAppNameSettingsIndexRoute
  otherAppNameActionsDownIndexRoute: typeof otherAppNameActionsDownIndexRoute
  otherAppNameActionsFilesIndexRoute: typeof otherAppNameActionsFilesIndexRoute
  otherAppNameSettingsNounpronsIndexRoute: typeof otherAppNameSettingsNounpronsIndexRoute
}

const otherAppNameRouteRouteChildren: otherAppNameRouteRouteChildren = {
  otherAppNameIndexRoute: otherAppNameIndexRoute,
  otherAppNameSettingsConsoleRoute: otherAppNameSettingsConsoleRoute,
  otherAppNameSettingsRightsRoute: otherAppNameSettingsRightsRoute,
  otherAppNameActionsIndexRoute: otherAppNameActionsIndexRoute,
  otherAppNameAuthIndexRoute: otherAppNameAuthIndexRoute,
  otherAppNameSchsIndexRoute: otherAppNameSchsIndexRoute,
  otherAppNameSettingsIndexRoute: otherAppNameSettingsIndexRoute,
  otherAppNameActionsDownIndexRoute: otherAppNameActionsDownIndexRoute,
  otherAppNameActionsFilesIndexRoute: otherAppNameActionsFilesIndexRoute,
  otherAppNameSettingsNounpronsIndexRoute:
    otherAppNameSettingsNounpronsIndexRoute,
}

const otherAppNameRouteRouteWithChildren =
  otherAppNameRouteRoute._addFileChildren(otherAppNameRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bible': typeof BibleRouteRouteWithChildren
  '/cm': typeof CmRouteRouteWithChildren
  '/tuner': typeof TunerRouteRouteWithChildren
  '/gamer': typeof GamerRouteLazyRouteWithChildren
  '/q': typeof QRouteLazyRouteWithChildren
  '/storages': typeof StoragesRouteLazyRouteWithChildren
  '/!other/$appName': typeof otherAppNameRouteRouteWithChildren
  '/bible/i': typeof BibleIRoute
  '/bible/search': typeof BibleSearchRoute
  '/bible/tran': typeof BibleTranRoute
  '/tuner/i': typeof TunerIRoute
  '/cm/edit': typeof CmEditRouteLazyRouteWithChildren
  '/q/i': typeof QILazyRoute
  '/bible/': typeof BibleIndexRoute
  '/cm/': typeof CmIndexRoute
  '/tuner/': typeof TunerIndexRoute
  '/gamer/': typeof GamerIndexLazyRoute
  '/presentation': typeof PresentationIndexLazyRoute
  '/schedule-day': typeof ScheduleDayIndexLazyRoute
  '/cm/li/events': typeof CmLiEventsRoute
  '/cm/li/fav': typeof CmLiFavRoute
  '/cm/li/sel': typeof CmLiSelRoute
  '/cm/edit/chord': typeof CmEditChordLazyRoute
  '/cm/edit/constant': typeof CmEditConstantLazyRoute
  '/cm/edit/e-e': typeof CmEditEELazyRoute
  '/cm/edit/events': typeof CmEditEventsLazyRoute
  '/cm/edit/mp3Rules': typeof CmEditMp3RulesLazyRoute
  '/q/a/$blank': typeof QABlankLazyRoute
  '/q/r/$blank': typeof QRBlankLazyRoute
  '/!other/$appName/': typeof otherAppNameIndexRoute
  '/cm/i': typeof CmIIndexRoute
  '/cm/li': typeof CmLiIndexRoute
  '/cm/player': typeof CmPlayerIndexRoute
  '/cm/edit/': typeof CmEditIndexLazyRoute
  '/gamer/i': typeof GamerIIndexLazyRoute
  '/q/a': typeof QAIndexLazyRoute
  '/q/r': typeof QRIndexLazyRoute
  '/schedule-day/$schw': typeof ScheduleDaySchwIndexLazyRoute
  '/storages/i': typeof StoragesIIndexLazyRoute
  '/!other/$appName/settings/console': typeof otherAppNameSettingsConsoleRoute
  '/!other/$appName/settings/rights': typeof otherAppNameSettingsRightsRoute
  '/cm/li/cat/$catw': typeof CmLiCatCatwRoute
  '/!other/$appName/actions': typeof otherAppNameActionsIndexRoute
  '/!other/$appName/auth': typeof otherAppNameAuthIndexRoute
  '/!other/$appName/schs': typeof otherAppNameSchsIndexRoute
  '/!other/$appName/settings': typeof otherAppNameSettingsIndexRoute
  '/cm/edit/coms': typeof CmEditComsIndexLazyRoute
  '/gamer/i/memory-giant': typeof GamerIMemoryGiantIndexLazyRoute
  '/storages/i/$rackw': typeof StoragesIRackwIndexLazyRoute
  '/!other/$appName/actions/down': typeof otherAppNameActionsDownIndexRoute
  '/!other/$appName/actions/files': typeof otherAppNameActionsFilesIndexRoute
  '/!other/$appName/settings/noun_prons': typeof otherAppNameSettingsNounpronsIndexRoute
  '/storages/i/$rackw/sum': typeof StoragesIRackwSumIndexRoute
  '/cm/edit/coms/$comw': typeof CmEditComsComwIndexLazyRoute
  '/storages/i/$rackw/$cardi': typeof StoragesIRackwCardiIndexLazyRoute
  '/storages/i/$rackw/edit': typeof StoragesIRackwEditIndexLazyRoute
  '/cm/edit/coms/$comw/$tab': typeof CmEditComsComwTabIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/q': typeof QRouteLazyRouteWithChildren
  '/storages': typeof StoragesRouteLazyRouteWithChildren
  '/bible/i': typeof BibleIRoute
  '/bible/search': typeof BibleSearchRoute
  '/bible/tran': typeof BibleTranRoute
  '/tuner/i': typeof TunerIRoute
  '/q/i': typeof QILazyRoute
  '/bible': typeof BibleIndexRoute
  '/cm': typeof CmIndexRoute
  '/tuner': typeof TunerIndexRoute
  '/gamer': typeof GamerIndexLazyRoute
  '/presentation': typeof PresentationIndexLazyRoute
  '/schedule-day': typeof ScheduleDayIndexLazyRoute
  '/cm/li/events': typeof CmLiEventsRoute
  '/cm/li/fav': typeof CmLiFavRoute
  '/cm/li/sel': typeof CmLiSelRoute
  '/cm/edit/chord': typeof CmEditChordLazyRoute
  '/cm/edit/constant': typeof CmEditConstantLazyRoute
  '/cm/edit/e-e': typeof CmEditEELazyRoute
  '/cm/edit/events': typeof CmEditEventsLazyRoute
  '/cm/edit/mp3Rules': typeof CmEditMp3RulesLazyRoute
  '/q/a/$blank': typeof QABlankLazyRoute
  '/q/r/$blank': typeof QRBlankLazyRoute
  '/!other/$appName': typeof otherAppNameIndexRoute
  '/cm/i': typeof CmIIndexRoute
  '/cm/li': typeof CmLiIndexRoute
  '/cm/player': typeof CmPlayerIndexRoute
  '/cm/edit': typeof CmEditIndexLazyRoute
  '/gamer/i': typeof GamerIIndexLazyRoute
  '/q/a': typeof QAIndexLazyRoute
  '/q/r': typeof QRIndexLazyRoute
  '/schedule-day/$schw': typeof ScheduleDaySchwIndexLazyRoute
  '/storages/i': typeof StoragesIIndexLazyRoute
  '/!other/$appName/settings/console': typeof otherAppNameSettingsConsoleRoute
  '/!other/$appName/settings/rights': typeof otherAppNameSettingsRightsRoute
  '/cm/li/cat/$catw': typeof CmLiCatCatwRoute
  '/!other/$appName/actions': typeof otherAppNameActionsIndexRoute
  '/!other/$appName/auth': typeof otherAppNameAuthIndexRoute
  '/!other/$appName/schs': typeof otherAppNameSchsIndexRoute
  '/!other/$appName/settings': typeof otherAppNameSettingsIndexRoute
  '/cm/edit/coms': typeof CmEditComsIndexLazyRoute
  '/gamer/i/memory-giant': typeof GamerIMemoryGiantIndexLazyRoute
  '/storages/i/$rackw': typeof StoragesIRackwIndexLazyRoute
  '/!other/$appName/actions/down': typeof otherAppNameActionsDownIndexRoute
  '/!other/$appName/actions/files': typeof otherAppNameActionsFilesIndexRoute
  '/!other/$appName/settings/noun_prons': typeof otherAppNameSettingsNounpronsIndexRoute
  '/storages/i/$rackw/sum': typeof StoragesIRackwSumIndexRoute
  '/cm/edit/coms/$comw': typeof CmEditComsComwIndexLazyRoute
  '/storages/i/$rackw/$cardi': typeof StoragesIRackwCardiIndexLazyRoute
  '/storages/i/$rackw/edit': typeof StoragesIRackwEditIndexLazyRoute
  '/cm/edit/coms/$comw/$tab': typeof CmEditComsComwTabIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/bible': typeof BibleRouteRouteWithChildren
  '/cm': typeof CmRouteRouteWithChildren
  '/tuner': typeof TunerRouteRouteWithChildren
  '/gamer': typeof GamerRouteLazyRouteWithChildren
  '/q': typeof QRouteLazyRouteWithChildren
  '/storages': typeof StoragesRouteLazyRouteWithChildren
  '/!other/$appName': typeof otherAppNameRouteRouteWithChildren
  '/bible/i': typeof BibleIRoute
  '/bible/search': typeof BibleSearchRoute
  '/bible/tran': typeof BibleTranRoute
  '/tuner/i': typeof TunerIRoute
  '/cm/edit': typeof CmEditRouteLazyRouteWithChildren
  '/q/i': typeof QILazyRoute
  '/bible/': typeof BibleIndexRoute
  '/cm/': typeof CmIndexRoute
  '/tuner/': typeof TunerIndexRoute
  '/gamer/': typeof GamerIndexLazyRoute
  '/presentation/': typeof PresentationIndexLazyRoute
  '/schedule-day/': typeof ScheduleDayIndexLazyRoute
  '/cm/li/events': typeof CmLiEventsRoute
  '/cm/li/fav': typeof CmLiFavRoute
  '/cm/li/sel': typeof CmLiSelRoute
  '/cm/edit/chord': typeof CmEditChordLazyRoute
  '/cm/edit/constant': typeof CmEditConstantLazyRoute
  '/cm/edit/e-e': typeof CmEditEELazyRoute
  '/cm/edit/events': typeof CmEditEventsLazyRoute
  '/cm/edit/mp3Rules': typeof CmEditMp3RulesLazyRoute
  '/q/a/$blank': typeof QABlankLazyRoute
  '/q/r/$blank': typeof QRBlankLazyRoute
  '/!other/$appName/': typeof otherAppNameIndexRoute
  '/cm/i/': typeof CmIIndexRoute
  '/cm/li/': typeof CmLiIndexRoute
  '/cm/player/': typeof CmPlayerIndexRoute
  '/cm/edit/': typeof CmEditIndexLazyRoute
  '/gamer/i/': typeof GamerIIndexLazyRoute
  '/q/a/': typeof QAIndexLazyRoute
  '/q/r/': typeof QRIndexLazyRoute
  '/schedule-day/$schw/': typeof ScheduleDaySchwIndexLazyRoute
  '/storages/i/': typeof StoragesIIndexLazyRoute
  '/!other/$appName/settings/console': typeof otherAppNameSettingsConsoleRoute
  '/!other/$appName/settings/rights': typeof otherAppNameSettingsRightsRoute
  '/cm/li/cat/$catw': typeof CmLiCatCatwRoute
  '/!other/$appName/actions/': typeof otherAppNameActionsIndexRoute
  '/!other/$appName/auth/': typeof otherAppNameAuthIndexRoute
  '/!other/$appName/schs/': typeof otherAppNameSchsIndexRoute
  '/!other/$appName/settings/': typeof otherAppNameSettingsIndexRoute
  '/cm/edit/coms/': typeof CmEditComsIndexLazyRoute
  '/gamer/i/memory-giant/': typeof GamerIMemoryGiantIndexLazyRoute
  '/storages/i/$rackw/': typeof StoragesIRackwIndexLazyRoute
  '/!other/$appName/actions/down/': typeof otherAppNameActionsDownIndexRoute
  '/!other/$appName/actions/files/': typeof otherAppNameActionsFilesIndexRoute
  '/!other/$appName/settings/noun_prons/': typeof otherAppNameSettingsNounpronsIndexRoute
  '/storages/i/$rackw/sum/': typeof StoragesIRackwSumIndexRoute
  '/cm/edit/coms/$comw/': typeof CmEditComsComwIndexLazyRoute
  '/storages/i/$rackw/$cardi/': typeof StoragesIRackwCardiIndexLazyRoute
  '/storages/i/$rackw/edit/': typeof StoragesIRackwEditIndexLazyRoute
  '/cm/edit/coms/$comw/$tab/': typeof CmEditComsComwTabIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bible'
    | '/cm'
    | '/tuner'
    | '/gamer'
    | '/q'
    | '/storages'
    | '/!other/$appName'
    | '/bible/i'
    | '/bible/search'
    | '/bible/tran'
    | '/tuner/i'
    | '/cm/edit'
    | '/q/i'
    | '/bible/'
    | '/cm/'
    | '/tuner/'
    | '/gamer/'
    | '/presentation'
    | '/schedule-day'
    | '/cm/li/events'
    | '/cm/li/fav'
    | '/cm/li/sel'
    | '/cm/edit/chord'
    | '/cm/edit/constant'
    | '/cm/edit/e-e'
    | '/cm/edit/events'
    | '/cm/edit/mp3Rules'
    | '/q/a/$blank'
    | '/q/r/$blank'
    | '/!other/$appName/'
    | '/cm/i'
    | '/cm/li'
    | '/cm/player'
    | '/cm/edit/'
    | '/gamer/i'
    | '/q/a'
    | '/q/r'
    | '/schedule-day/$schw'
    | '/storages/i'
    | '/!other/$appName/settings/console'
    | '/!other/$appName/settings/rights'
    | '/cm/li/cat/$catw'
    | '/!other/$appName/actions'
    | '/!other/$appName/auth'
    | '/!other/$appName/schs'
    | '/!other/$appName/settings'
    | '/cm/edit/coms'
    | '/gamer/i/memory-giant'
    | '/storages/i/$rackw'
    | '/!other/$appName/actions/down'
    | '/!other/$appName/actions/files'
    | '/!other/$appName/settings/noun_prons'
    | '/storages/i/$rackw/sum'
    | '/cm/edit/coms/$comw'
    | '/storages/i/$rackw/$cardi'
    | '/storages/i/$rackw/edit'
    | '/cm/edit/coms/$comw/$tab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/q'
    | '/storages'
    | '/bible/i'
    | '/bible/search'
    | '/bible/tran'
    | '/tuner/i'
    | '/q/i'
    | '/bible'
    | '/cm'
    | '/tuner'
    | '/gamer'
    | '/presentation'
    | '/schedule-day'
    | '/cm/li/events'
    | '/cm/li/fav'
    | '/cm/li/sel'
    | '/cm/edit/chord'
    | '/cm/edit/constant'
    | '/cm/edit/e-e'
    | '/cm/edit/events'
    | '/cm/edit/mp3Rules'
    | '/q/a/$blank'
    | '/q/r/$blank'
    | '/!other/$appName'
    | '/cm/i'
    | '/cm/li'
    | '/cm/player'
    | '/cm/edit'
    | '/gamer/i'
    | '/q/a'
    | '/q/r'
    | '/schedule-day/$schw'
    | '/storages/i'
    | '/!other/$appName/settings/console'
    | '/!other/$appName/settings/rights'
    | '/cm/li/cat/$catw'
    | '/!other/$appName/actions'
    | '/!other/$appName/auth'
    | '/!other/$appName/schs'
    | '/!other/$appName/settings'
    | '/cm/edit/coms'
    | '/gamer/i/memory-giant'
    | '/storages/i/$rackw'
    | '/!other/$appName/actions/down'
    | '/!other/$appName/actions/files'
    | '/!other/$appName/settings/noun_prons'
    | '/storages/i/$rackw/sum'
    | '/cm/edit/coms/$comw'
    | '/storages/i/$rackw/$cardi'
    | '/storages/i/$rackw/edit'
    | '/cm/edit/coms/$comw/$tab'
  id:
    | '__root__'
    | '/'
    | '/bible'
    | '/cm'
    | '/tuner'
    | '/gamer'
    | '/q'
    | '/storages'
    | '/!other/$appName'
    | '/bible/i'
    | '/bible/search'
    | '/bible/tran'
    | '/tuner/i'
    | '/cm/edit'
    | '/q/i'
    | '/bible/'
    | '/cm/'
    | '/tuner/'
    | '/gamer/'
    | '/presentation/'
    | '/schedule-day/'
    | '/cm/li/events'
    | '/cm/li/fav'
    | '/cm/li/sel'
    | '/cm/edit/chord'
    | '/cm/edit/constant'
    | '/cm/edit/e-e'
    | '/cm/edit/events'
    | '/cm/edit/mp3Rules'
    | '/q/a/$blank'
    | '/q/r/$blank'
    | '/!other/$appName/'
    | '/cm/i/'
    | '/cm/li/'
    | '/cm/player/'
    | '/cm/edit/'
    | '/gamer/i/'
    | '/q/a/'
    | '/q/r/'
    | '/schedule-day/$schw/'
    | '/storages/i/'
    | '/!other/$appName/settings/console'
    | '/!other/$appName/settings/rights'
    | '/cm/li/cat/$catw'
    | '/!other/$appName/actions/'
    | '/!other/$appName/auth/'
    | '/!other/$appName/schs/'
    | '/!other/$appName/settings/'
    | '/cm/edit/coms/'
    | '/gamer/i/memory-giant/'
    | '/storages/i/$rackw/'
    | '/!other/$appName/actions/down/'
    | '/!other/$appName/actions/files/'
    | '/!other/$appName/settings/noun_prons/'
    | '/storages/i/$rackw/sum/'
    | '/cm/edit/coms/$comw/'
    | '/storages/i/$rackw/$cardi/'
    | '/storages/i/$rackw/edit/'
    | '/cm/edit/coms/$comw/$tab/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibleRouteRoute: typeof BibleRouteRouteWithChildren
  CmRouteRoute: typeof CmRouteRouteWithChildren
  TunerRouteRoute: typeof TunerRouteRouteWithChildren
  GamerRouteLazyRoute: typeof GamerRouteLazyRouteWithChildren
  QRouteLazyRoute: typeof QRouteLazyRouteWithChildren
  StoragesRouteLazyRoute: typeof StoragesRouteLazyRouteWithChildren
  otherAppNameRouteRoute: typeof otherAppNameRouteRouteWithChildren
  PresentationIndexLazyRoute: typeof PresentationIndexLazyRoute
  ScheduleDayIndexLazyRoute: typeof ScheduleDayIndexLazyRoute
  ScheduleDaySchwIndexLazyRoute: typeof ScheduleDaySchwIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibleRouteRoute: BibleRouteRouteWithChildren,
  CmRouteRoute: CmRouteRouteWithChildren,
  TunerRouteRoute: TunerRouteRouteWithChildren,
  GamerRouteLazyRoute: GamerRouteLazyRouteWithChildren,
  QRouteLazyRoute: QRouteLazyRouteWithChildren,
  StoragesRouteLazyRoute: StoragesRouteLazyRouteWithChildren,
  otherAppNameRouteRoute: otherAppNameRouteRouteWithChildren,
  PresentationIndexLazyRoute: PresentationIndexLazyRoute,
  ScheduleDayIndexLazyRoute: ScheduleDayIndexLazyRoute,
  ScheduleDaySchwIndexLazyRoute: ScheduleDaySchwIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bible",
        "/cm",
        "/tuner",
        "/gamer",
        "/q",
        "/storages",
        "/!other/$appName",
        "/presentation/",
        "/schedule-day/",
        "/schedule-day/$schw/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/bible": {
      "filePath": "bible/route.tsx",
      "children": [
        "/bible/i",
        "/bible/search",
        "/bible/tran",
        "/bible/"
      ]
    },
    "/cm": {
      "filePath": "cm/route.tsx",
      "children": [
        "/cm/edit",
        "/cm/",
        "/cm/li/events",
        "/cm/li/fav",
        "/cm/li/sel",
        "/cm/i/",
        "/cm/li/",
        "/cm/player/",
        "/cm/li/cat/$catw"
      ]
    },
    "/tuner": {
      "filePath": "tuner/route.tsx",
      "children": [
        "/tuner/i",
        "/tuner/"
      ]
    },
    "/gamer": {
      "filePath": "gamer/route.lazy.tsx",
      "children": [
        "/gamer/",
        "/gamer/i/",
        "/gamer/i/memory-giant/"
      ]
    },
    "/q": {
      "filePath": "q/route.lazy.tsx",
      "children": [
        "/q/i",
        "/q/a/$blank",
        "/q/r/$blank",
        "/q/a/",
        "/q/r/"
      ]
    },
    "/storages": {
      "filePath": "storages/route.lazy.tsx",
      "children": [
        "/storages/i/",
        "/storages/i/$rackw/",
        "/storages/i/$rackw/sum/",
        "/storages/i/$rackw/$cardi/",
        "/storages/i/$rackw/edit/"
      ]
    },
    "/!other/$appName": {
      "filePath": "!other.$appName/route.tsx",
      "children": [
        "/!other/$appName/",
        "/!other/$appName/settings/console",
        "/!other/$appName/settings/rights",
        "/!other/$appName/actions/",
        "/!other/$appName/auth/",
        "/!other/$appName/schs/",
        "/!other/$appName/settings/",
        "/!other/$appName/actions/down/",
        "/!other/$appName/actions/files/",
        "/!other/$appName/settings/noun_prons/"
      ]
    },
    "/bible/i": {
      "filePath": "bible/i.tsx",
      "parent": "/bible"
    },
    "/bible/search": {
      "filePath": "bible/search.tsx",
      "parent": "/bible"
    },
    "/bible/tran": {
      "filePath": "bible/tran.tsx",
      "parent": "/bible"
    },
    "/tuner/i": {
      "filePath": "tuner/i.tsx",
      "parent": "/tuner"
    },
    "/cm/edit": {
      "filePath": "cm/edit/route.lazy.tsx",
      "parent": "/cm",
      "children": [
        "/cm/edit/chord",
        "/cm/edit/constant",
        "/cm/edit/e-e",
        "/cm/edit/events",
        "/cm/edit/mp3Rules",
        "/cm/edit/",
        "/cm/edit/coms/",
        "/cm/edit/coms/$comw/",
        "/cm/edit/coms/$comw/$tab/"
      ]
    },
    "/q/i": {
      "filePath": "q/i.lazy.tsx",
      "parent": "/q"
    },
    "/bible/": {
      "filePath": "bible/index.tsx",
      "parent": "/bible"
    },
    "/cm/": {
      "filePath": "cm/index.tsx",
      "parent": "/cm"
    },
    "/tuner/": {
      "filePath": "tuner/index.tsx",
      "parent": "/tuner"
    },
    "/gamer/": {
      "filePath": "gamer/index.lazy.tsx",
      "parent": "/gamer"
    },
    "/presentation/": {
      "filePath": "presentation/index.lazy.tsx"
    },
    "/schedule-day/": {
      "filePath": "schedule-day/index.lazy.tsx"
    },
    "/cm/li/events": {
      "filePath": "cm/li/events.tsx",
      "parent": "/cm"
    },
    "/cm/li/fav": {
      "filePath": "cm/li/fav.tsx",
      "parent": "/cm"
    },
    "/cm/li/sel": {
      "filePath": "cm/li/sel.tsx",
      "parent": "/cm"
    },
    "/cm/edit/chord": {
      "filePath": "cm/edit/chord.lazy.tsx",
      "parent": "/cm/edit"
    },
    "/cm/edit/constant": {
      "filePath": "cm/edit/constant.lazy.tsx",
      "parent": "/cm/edit"
    },
    "/cm/edit/e-e": {
      "filePath": "cm/edit/e-e.lazy.tsx",
      "parent": "/cm/edit"
    },
    "/cm/edit/events": {
      "filePath": "cm/edit/events.lazy.tsx",
      "parent": "/cm/edit"
    },
    "/cm/edit/mp3Rules": {
      "filePath": "cm/edit/mp3Rules.lazy.tsx",
      "parent": "/cm/edit"
    },
    "/q/a/$blank": {
      "filePath": "q/a/$blank.lazy.tsx",
      "parent": "/q"
    },
    "/q/r/$blank": {
      "filePath": "q/r/$blank.lazy.tsx",
      "parent": "/q"
    },
    "/!other/$appName/": {
      "filePath": "!other.$appName/index.tsx",
      "parent": "/!other/$appName"
    },
    "/cm/i/": {
      "filePath": "cm/i/index.tsx",
      "parent": "/cm"
    },
    "/cm/li/": {
      "filePath": "cm/li/index.tsx",
      "parent": "/cm"
    },
    "/cm/player/": {
      "filePath": "cm/player/index.tsx",
      "parent": "/cm"
    },
    "/cm/edit/": {
      "filePath": "cm/edit/index.lazy.tsx",
      "parent": "/cm/edit"
    },
    "/gamer/i/": {
      "filePath": "gamer/i/index.lazy.tsx",
      "parent": "/gamer"
    },
    "/q/a/": {
      "filePath": "q/a/index.lazy.tsx",
      "parent": "/q"
    },
    "/q/r/": {
      "filePath": "q/r/index.lazy.tsx",
      "parent": "/q"
    },
    "/schedule-day/$schw/": {
      "filePath": "schedule-day/$schw/index.lazy.tsx"
    },
    "/storages/i/": {
      "filePath": "storages/i/index.lazy.tsx",
      "parent": "/storages"
    },
    "/!other/$appName/settings/console": {
      "filePath": "!other.$appName/settings/console.tsx",
      "parent": "/!other/$appName"
    },
    "/!other/$appName/settings/rights": {
      "filePath": "!other.$appName/settings/rights.tsx",
      "parent": "/!other/$appName"
    },
    "/cm/li/cat/$catw": {
      "filePath": "cm/li/cat.$catw.tsx",
      "parent": "/cm"
    },
    "/!other/$appName/actions/": {
      "filePath": "!other.$appName/actions/index.tsx",
      "parent": "/!other/$appName"
    },
    "/!other/$appName/auth/": {
      "filePath": "!other.$appName/auth/index.tsx",
      "parent": "/!other/$appName"
    },
    "/!other/$appName/schs/": {
      "filePath": "!other.$appName/schs/index.tsx",
      "parent": "/!other/$appName"
    },
    "/!other/$appName/settings/": {
      "filePath": "!other.$appName/settings/index.tsx",
      "parent": "/!other/$appName"
    },
    "/cm/edit/coms/": {
      "filePath": "cm/edit/coms/index.lazy.tsx",
      "parent": "/cm/edit"
    },
    "/gamer/i/memory-giant/": {
      "filePath": "gamer/i/memory-giant/index.lazy.tsx",
      "parent": "/gamer"
    },
    "/storages/i/$rackw/": {
      "filePath": "storages/i/$rackw/index.lazy.tsx",
      "parent": "/storages"
    },
    "/!other/$appName/actions/down/": {
      "filePath": "!other.$appName/actions/down/index.tsx",
      "parent": "/!other/$appName"
    },
    "/!other/$appName/actions/files/": {
      "filePath": "!other.$appName/actions/files/index.tsx",
      "parent": "/!other/$appName"
    },
    "/!other/$appName/settings/noun_prons/": {
      "filePath": "!other.$appName/settings/noun_prons/index.tsx",
      "parent": "/!other/$appName"
    },
    "/storages/i/$rackw/sum/": {
      "filePath": "storages/i/$rackw/sum/index.tsx",
      "parent": "/storages"
    },
    "/cm/edit/coms/$comw/": {
      "filePath": "cm/edit/coms/$comw/index.lazy.tsx",
      "parent": "/cm/edit"
    },
    "/storages/i/$rackw/$cardi/": {
      "filePath": "storages/i/$rackw/$cardi/index.lazy.tsx",
      "parent": "/storages"
    },
    "/storages/i/$rackw/edit/": {
      "filePath": "storages/i/$rackw/edit/index.lazy.tsx",
      "parent": "/storages"
    },
    "/cm/edit/coms/$comw/$tab/": {
      "filePath": "cm/edit/coms/$comw/$tab/index.lazy.tsx",
      "parent": "/cm/edit"
    }
  }
}
ROUTE_MANIFEST_END */
